sun tests

diff --git a/mpirtest b/mpirtest
--- a/mpirtest
+++ b/mpirtest
@@ -1,6 +1,14 @@
 #!/bin/bash
 # copy this file to mpir root and run it
 
+function build {
+mkdir $SYSNAME && cd $SYSNAME && ../configure $1 && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
+if [ $? -ne 0 ] ; then echo "FAILED with options $1" ; exit 1 ; fi
+}
+
+
+touch demos/calc/*.c demos/calc/*.h
+
 SYSNAME=$(uname -n)
 if [ -e $SYSNAME ] ; then echo "ERROR directory $SYSNAME allready exist" ; exit 1 ; fi
 
@@ -25,10 +33,11 @@ if [ $SYS == "x86_64" ] ; then FAT=1 ; fi
 if [ $SYS == "x86" ] ; then FAT=1 ; fi
 
 # standard build
-OPT=""
+build ""
 # all features
-OPT="--enable-cxx --enable-gmpcompat"
+build "--enable-cxx --enable-gmpcompat"
 # all features and debug
+exit
 OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
 # maximum debug
 OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug --build=none"
@@ -40,11 +49,6 @@ if [ $FAT -eq 1 ] ; then
 	# all features and debug
 	OPT="--enable-fat --enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
 fi
-
-
-mkdir $SYSNAME && cd $SYSNAME && ../configure $OPT && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
-if [ $? -ne 0 ] ; then echo "FAILED with options $OPT" ; exit 1 ; fi
-
 
 
 # try differnt gcc , build try 
