test stuff

diff --git a/mpirtest b/mpirtest
--- a/mpirtest
+++ b/mpirtest
@@ -1,13 +1,20 @@
 #!/bin/bash
-# copy this file to mpir root and run it
+# run this in the directory where everything will be built
+# first param is mpir directory
 
-function build {
-mkdir $SYSNAME && cd $SYSNAME && ../configure $1 && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
-if [ $? -ne 0 ] ; then echo "FAILED with options $1" ; exit 1 ; fi
-}
+DIR=$(pwd)
+if [ $# -eq 1 ] ; then 
+	# get absolute directory
+	REL=$(echo $1 | head -c 1)
+	if [ $REL == "/" ] ; then
+	       DIR=$1
+	else
+	       DIR=$(pwd)/$1
+	fi
+fi
 
-
-touch demos/calc/*.c demos/calc/*.h
+# dont want to run yacc
+touch $DIR/demos/calc/*.c $DIR/demos/calc/*.h
 
 SYSNAME=$(uname -n)
 if [ -e $SYSNAME ] ; then echo "ERROR directory $SYSNAME allready exist" ; exit 1 ; fi
@@ -28,26 +35,31 @@ fi
 echo "Using $CPUS cpus"
 
 FAT=0
-SYS=$(./configfsf.guess | cut -f 1 -d -)
+SYS=$($DIR/configfsf.guess | cut -f 1 -d -)
 if [ $SYS == "x86_64" ] ; then FAT=1 ; fi
 if [ $SYS == "x86" ] ; then FAT=1 ; fi
+
+function build {
+mkdir $SYSNAME && cd $SYSNAME && $DIR/configure $1 && make -j $CPUS && make -j $CPUS check && cd .. && rm -rf $SYSNAME
+if [ $? -ne 0 ] ; then echo "FAILED with options $1" ; exit 1 ; fi
+}
+
 
 # standard build
 build ""
 # all features
 build "--enable-cxx --enable-gmpcompat"
 # all features and debug
-exit
-OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
+build "--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
 # maximum debug
-OPT="--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug --build=none"
+build "--enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug --build=none"
 if [ $FAT -eq 1 ] ; then
 	# standard build
-	OPT="--enable-fat"
+	build "--enable-fat"
 	# all features
-	OPT="--enable-fat --enable-cxx --enable-gmpcompat"
+	build "--enable-fat --enable-cxx --enable-gmpcompat"
 	# all features and debug
-	OPT="--enable-fat --enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
+	build "--enable-fat --enable-cxx --enable-gmpcompat --enable-assert --enable-alloca=debug"
 fi
 
 
